import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
// import AppHeader from "@/components/shared/AppHeader";
import Sider from "antd/es/layout/Sider";
import AppSideMenu from "@/components/shared/AppSideMenu";
import ToggleTheme from "@/components/ToggleTheme";

const inter = Inter({ subsets: ["latin"], display: 'swap', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToggleTheme
          attribute="class"
          defaultTheme=""
          enableSystem
          disableTransitionOnChange
        >
          <AntdRegistry>
            <Layout>
              {/* <AppHeader /> */}
              <Layout>
                <Sider
                theme="light"
                  style={{
                    position: "fixed",
                    top: 0,
                    left: 0,
                    borderRight: "1px solid #f1f1f1",
                    height: "100vh",
                  }}
                >
                  <div className="flex justify-center py-5">
                    <h1 className="text-xl"><span className="font-bold ">DREAM</span> PARK</h1>
                  </div>
                  <AppSideMenu />
                </Sider>
                <Layout style={{ marginLeft: "200px" }}>
                  <Content
                    style={{ padding: "16px",  minHeight: "calc(100vh - 64px)" }}
                  >
                    {" "}
                    {children}
                  </Content>
                </Layout>
              </Layout>
            </Layout>
          </AntdRegistry>
        </ToggleTheme>
      </body>
    </html>
  );
}
